const express = require("express");
const router = express.Router();
const {
  BUILDINGHEADWISEREPORT,
  DPDCHEADWISEREPORT,
  SHDORHEADWISEREPORT,
  NABARDHEADWISEREPORT,
  CRFHEADWISEREPORT,
  MASTERHEADWISEREPOSTBuilding,
  MASTERHEADWISEREPOSTRoad,
  MASTERHEADWISEREPOSTCRF,
  MASTERHEADWISEREPOSTNabard,
  MASTERHEADWISEREPOSTAnnuity
} = require("../controllers/masterHeadWiseController");

// Route to get upcoming due dates (next 20 days)
router.post("/BUILDINGHEADWISEREPORT", BUILDINGHEADWISEREPORT);
router.post("/DPDCHEADWISEREPORT", DPDCHEADWISEREPORT);
router.post("/SHDORHEADWISEREPORT", SHDORHEADWISEREPORT);
router.post("/NABARDHEADWISEREPORT", NABARDHEADWISEREPORT);
router.post("/CRFHEADWISEREPORT", CRFHEADWISEREPORT);

//Master Individual report routes
router.post("/MASTERHEADWISEREPOSTBuilding", MASTERHEADWISEREPOSTBuilding);
router.post("/MASTERHEADWISEREPOSTRoad", MASTERHEADWISEREPOSTRoad);
router.post("/MASTERHEADWISEREPOSTCRF", MASTERHEADWISEREPOSTCRF);
router.post("/MASTERHEADWISEREPOSTNabard", MASTERHEADWISEREPOSTNabard);
router.post("/MASTERHEADWISEREPOSTAnnuity", MASTERHEADWISEREPOSTAnnuity);




module.exports = router;
